/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.2.1.1                                               */
/*  Date (dd.mm.yyyy):  8. 4.2023   Time (hh:mm): 06:35                        */
/*******************************************************************************/


#ifndef _GUIX_DISPLAY_1_RESOURCES_H_
#define _GUIX_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 800
#define DISPLAY_1_Y_RESOLUTION 480
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define DISPLAY_1_COLOR_TABLE_SIZE 29

/* Font ID definitions                                                         */

#define DISPLAY_1_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define DISPLAY_1_PIXELMAP_TABLE_SIZE 5

/* String Ids                                                                  */

#define GX_STRING_ID_HELLO_WORLD 1
#define GX_STRING_ID_CHECKBOX_TEXT 2
#define GX_STRING_ID_BUTTON_DISABLED 3
#define GX_STRING_ID_BUTTON_ENABLED 4
#define GX_STRING_ID_INSTRUCT_CHECKBOX 5
#define GX_STRING_ID_WINDOW1 6
#define GX_STRING_ID_WINDOW2 7
#define GX_STRING_ID_INSTRUCT_BUTTON 8
#define DISPLAY_1_STRING_TABLE_SIZE 9

#endif                                       /* sentry                         */
