/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.2.1.1                                               */
/*  Date (dd.mm.yyyy): 15. 4.2023   Time (hh:mm): 15:41                        */
/*******************************************************************************/


#ifndef _AUDIO_PLAYER_DISPLAY_1_RESOURCES_H_
#define _AUDIO_PLAYER_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 800
#define DISPLAY_1_Y_RESOLUTION 480
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define DISPLAY_1_COLOR_TABLE_SIZE 29

/* Font ID definitions                                                         */

#define GX_FONT_ID_SMALL 4
#define GX_FONT_ID_MEDIUM 5
#define GX_FONT_ID_LARGE 6
#define DISPLAY_1_FONT_TABLE_SIZE 7

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_BAR_VOL 5
#define GX_PIXELMAP_ID_BG 6
#define GX_PIXELMAP_ID_BTN_CIRCLE 7
#define GX_PIXELMAP_ID_BTN_DOWN 8
#define GX_PIXELMAP_ID_BTN_EJECT 9
#define GX_PIXELMAP_ID_BTN_FWD 10
#define GX_PIXELMAP_ID_BTN_PAUSE 11
#define GX_PIXELMAP_ID_BTN_PLAY 12
#define GX_PIXELMAP_ID_BTN_RESTART 13
#define GX_PIXELMAP_ID_BTN_REW 14
#define GX_PIXELMAP_ID_BTN_UP 15
#define GX_PIXELMAP_ID_BTN_VOL_DOWN 16
#define GX_PIXELMAP_ID_BTN_VOL_UP 17
#define GX_PIXELMAP_ID_ICO_LOGO 18
#define GX_PIXELMAP_ID_ICO_USB 19
#define GX_PIXELMAP_ID_OVERLAY 20
#define GX_PIXELMAP_ID_OVERLAY_BOTTOM 21
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 22

/* String Ids                                                                  */

#define GX_STRING_ID_VERSION 1
#define GX_STRING_ID_PLAYING 2
#define GX_STRING_ID_PAUSED 3
#define GX_STRING_ID_STOPPED 4
#define GX_STRING_ID_BLANK 5
#define GX_STRING_ID_USB_1 6
#define GX_STRING_ID_USB_2 7
#define GX_STRING_ID_STRING 8
#define GX_STRING_ID_ERR_OPEN 9
#define GX_STRING_ID_ERR_PAUSE 10
#define GX_STRING_ID_ERR_RESUME 11
#define GX_STRING_ID_ERR_CLOSE 12
#define GX_STRING_ID_ERR_VOLUME 13
#define GX_STRING_ID_ERR_PLAYBACK 14
#define GX_STRING_ID_ERR_NOT_RIFF 15
#define GX_STRING_ID_ERR_NOT_WAVE 16
#define GX_STRING_ID_ERR_NOT_PCM 17
#define GX_STRING_ID_ERR_NOT_MONO 18
#define GX_STRING_ID_ERR_NOT_44KHZ 19
#define GX_STRING_ID_ERR_NOT_16BIT 20
#define GX_STRING_ID_ERR_NO_DATA_CHUNK 21
#define DISPLAY_1_STRING_TABLE_SIZE 22

#endif                                       /* sentry                         */
